name: DEPLOY CHOSEN ENVIRONMENT

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'ENVIRONMENT TO DEPLOY TO'
        required: true
        default: 'nonprod'
        type: environment
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: ${{ env.AWS_DEPLOYMENT_ROLE_TO_ASSUME_ARN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Terraform Format
        working-directory: infra
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra
        id: plan
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        working-directory: infra
#        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false tfplan