name: Deploy Non-Prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::467222377375:role/github-actions

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Terraform Format
        working-directory: infra
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra
        id: plan
        run: terraform plan -out=tfplan -var aws_region=us-east-2 -var aws_account=467222377375 -var aws_role_arn=arn:aws:iam::467222377375:role/terraform-readonly -var deploy_environment=nonprod

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply tfplan